fun main(){
//    testWhen()
//    testWhen2()
//    testWhen3()
//    testWhen4()
//    testWhen5()
//    testForInLoop()
//    testForInloop2()
//    testForInloop3()
//    testForLoop4()
//    testForLoop5()
//    testForLoopArray()
//    testForLoopString()
//    testWhileLoop()
//    testDoWhile()
//    testBreakExpress()
//    testBreakExpress2()
    testBreakExpress3()
}